version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE

  notification-service:
    image: notification-service
    ports: 
      - 8000:8000
    environment:
      - DB_URI=$DB_URI
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_LOGIN=$SMTP_LOGIN
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_EMAIL=$SMTP_EMAIL
      - SMTP_NAME=$SMTP_NAME

  smtp:
    image: marcopas/docker-mailslurper
    restart: always
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085
